/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfficeOfficeIdRouteImport } from './routes/office.$officeId'

const OfficeOfficeIdRoute = OfficeOfficeIdRouteImport.update({
  id: '/office/$officeId',
  path: '/office/$officeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/office/$officeId': typeof OfficeOfficeIdRoute
}
export interface FileRoutesByTo {
  '/office/$officeId': typeof OfficeOfficeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/office/$officeId': typeof OfficeOfficeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/office/$officeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/office/$officeId'
  id: '__root__' | '/office/$officeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OfficeOfficeIdRoute: typeof OfficeOfficeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/office/$officeId': {
      id: '/office/$officeId'
      path: '/office/$officeId'
      fullPath: '/office/$officeId'
      preLoaderRoute: typeof OfficeOfficeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  OfficeOfficeIdRoute: OfficeOfficeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
